### PR TITLE
Add support for getting email and fullname from ldap

### PR DESCRIPTION
**Pull request by Shelnutt2**
This add the support needed for getting email and fullname from LDAP. I've test and its functioning against taiga 1.6

### CODE REVIEW

**Comment by artlepool** [comment]
Hi @Shelnutt2 

I forked @ensky's repo too as I also have a solution for LDAP authentication that I wrote for my company.
Its along the same lines as yours but with an addition to make it a bit more flexible - we use a service account to search for the username in our LDAP structure as not all our users are in the same OU (we have multiple offices)

The service account searches for the username, then returns the DN.  We then try and authenticate the DN username with the password the user has entered to authenticate them.

There doesn't seem to be a hurry for this merge request to be accepted, so should I commit to your fork or create my own so you can see my solution?

**Comment by Shelnutt2** [comment]
@artlepool which ever you prefer to do. I'm not sure if @ensky is around, as there been no activity here. If you want to commit to mine I'll give you rights to it. Or you can push it yourself. If you have a more elegant solution it'll superseed my patchset.

**Comment by ensky** [comment]
Hi guys, I've missed the merge request mail, sorry for that.
@Shelnutt2 thanks for this merge, it looks nice, but since @artlepool has another solution for this, maybe we could wait for his MR and see which should we use?

I'm a pretty newbie to LDAP, so if you like to further maintain this project, just write a repo link on this issue request https://github.com/taigaio/taiga-back/issues/120 (though I thought there may need a taiga-contribute list to show it, instead of listing in a thread)

**Comment by artlepool** [comment]
Thanks guys.  As suggested by @ensky, I've created a separate MR #3 to try and keep things clean.  Details on there.

**Pull request closed without merging**
