### PR TITLE
Search for account in LDAP with matching username, then perform LDAP bind with that user

### PR DESCRIPTION
**Pull request by artlepool**
I have documented the authentication logic for this version in the README, underneath the config settings.

Couple of points:

a) Unit tests aren't my strong point! The existing unit tests don't work and I'm struggling to see how to write/update them so that they'd be useful, given you need to connect to an LDAP server to check if the code is working as it should.   Please feel free to suggest ideas and I'll be happy to update the tests.

b) Now that the login is doing two things (first searching for a matching user and then attempting a successful bind), it can take a number of seconds.  The login button on Taiga login page form doesn't seem to change state, eg. show a progress indicator, so the user doesn't have any feedback as to what is happening while the login process is taking place.  
I've hacked a solution in my instance that disables the username and password box and login button, and changes the text to "Signing In..." but it certainly isn't a good enough solution to raise a PR on taiga-front!

### CODE REVIEW

**Comment by Shelnutt2** [comment]
Looking through things here very nice solution. I've not tested it but my only concern is the requirement of a service account. I think if no binding username and password is set it should try an anonymous search. Currently in my use case we do not have service accounts but simply allow anonymous read only searches.

**Comment by ensky** [comment]
Looks pretty nice and elegant! And I also agree with @Shelnutt2 about the anonymous concern.

**Comment by artlepool** [comment]
That's a good point about the anonymous bind - I've added that to the code now. As suggested by @Shelnutt2, if LDAP_BIND_DN is not specified or is blank, then an anonymous bind is attempted.

@Shelnutt2 - I'm afraid I don't have the ability to test the anonymous bind given the setup that we have in my office here. The code does run without error for me, in that the anonymous bind executes without problems, it just doesn't return anything from the search.  Would appreciate it if you could give it a try and feedback!

**Comment by artlepool** [comment]
I've now tested the anonymous bind functionality after installing OpenLDAP locally. As intended, if the LDAP_BIND_DN config setting is not specified or is blank, an anonymous bind takes place to search for the user account, then an attempt is made to authenticate against LDAP server using the user account and login password.   If successful, then the user is logged in to Taiga.

Do we consider this ready for merge?

**Pull request merged**
